apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlserver-pv
  namespace: techchallenge
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/sqlserver