apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: techchallenge
spec:
  selector:
    app: grafana
  ports:
  - port: 3000 # não conflita com a porta da api pois são pods diferentes
    targetPort: 3000 
  type: NodePort