apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: techchallenge
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'dotnet-api'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: techchallenge;dotnet-api;http
      
      - job_name: 'grafana'
        static_configs:
          - targets: ['grafana.techchallenge.svc.cluster.local:3000']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.techchallenge.svc.cluster.local:9100']

      - job_name: 'rabbitmq'
        static_configs:
          - targets: ['rabbitmq.techchallenge.svc.cluster.local:15692']

      - job_name: 'cadvisor'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: http
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: cadvisor

      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: endpoints
        scheme: https
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: default;kubernetes;https

