apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: techchallenge
spec:
  selector:
    app: rabbitmq
  ports:
  - name: http-management
    port: 15672
    targetPort: 15672
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: metrics
    port: 15692
    targetPort: 15692
  type: NodePort