apiVersion: v1
kind: Service
metadata:
  name: dotnet-api
  namespace: techchallenge
spec:
  selector:
    app: dotnet-api
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    name: http # usado para o prometheus