apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-api
  namespace: techchallenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
      - name: dotnet-api
        image: techchallengeapi-dotnet-api:latest
        ports:
          - containerPort: 3000
        imagePullPolicy: IfNotPresent
        env:
          - name: CONNECTION_STRING
            value: "Server=sqlserver;Database=TechChallenge;User Id=sa;Password=MinhaSenhaForte123!;TrustServerCertificate=True;"